# -*- coding: utf-8 -*-
"""ML_crush.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDPFEsf_CeDAxy6krjwBH8_q2IIpQnAM
"""

!pip3 install pandas scikit-Learn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data= pd.DataFrame({
    'texts_per_day': [1,10,3,0,5,8,2,9,4,7,6,1,11,0,2,8],
    'emoji_usage':[0,1,0,0,1,1,0,1,1,1,1,0,1,0,0,1],
    'left_on_read':[1,0,1,1,0,0,1,0,0,0,1,1,0,0,1,1],
    'asked_you_out':[0,1,0,0,1,1,0,1,1,1,0,0,1,1,0,0],
    'plans_a_date':[0,1,0,0,1,1,0,1,1,0,1,1,1,0,0,1],
    'buys_you_flowers':[1,1,0,0,0,1,1,1,1,0,0,1,1,0,0,0],
    'buys_you_matcha':[0,1,0,0,1,1,0,1,1,0,0,0,1,0,1,1],
    'buys_you_fries':[0,1,0,0,1,1,0,1,1,0,0,0,1,0,0,1],
    'likes_you':[0,1,0,0,1,1,0,1,1,0,1,1,1,0,1,0]
})

data

X= data.drop('likes_you',axis=1)
y= data['likes_you']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=15)

model= LogisticRegression()
model.fit(X_train,y_train)

from sklearn.metrics import accuracy_score

y_pred= model.predict(X_test)
accuracy= accuracy_score(y_test,y_pred)
print(f"Model accuracy: {accuracy * 100:.1f}%")

sample_person={
    'texts_per_day':0,
    'emoji_usage':0,
    'left_on_read':0,
    'asked_you_out':3,
    'plans_a_date':1,
    'buys_you_flowers':0,
    'buys_you_matcha':0,
    'buys_you_fries':0
}

input_df= pd.DataFrame([sample_person])

prob=model.predict_proba(input_df)[0][1]

if prob>0.8:
  print(f"💌 AI says: {prob*100:.1f}% chance your crush is totally into you!!!")
elif prob>0.5:
  print(f" 💌 AI says: {prob*100:.1f}% chance your crush likes you-could go either wayyy!!!")
else:
  print(f" 💌 AI says: only {prob * 100:.1f}% chance... might just like you as a friend mehh : ( !!! )")

